package app.cash.trifle

import app.cash.trifle.extensions.CertificateChain

/**
 * Class representing verified data extracted from a SignedData message after verification. Clients
 * should use this class to access their data, which should only be generated by verifying the
 * originating SignedData message.
 *
 * @property clientData - The provided by the Trifle client when creating a SignedData message.
 * @property certificateChain - List of certificates representing the certificate chain.
 */
data class VerifiedData internal constructor(
  val clientData: ByteArray,
  val certificateChain: CertificateChain
) {
  override fun equals(other: Any?): Boolean {
    if (this === other) return true
    if (javaClass != other?.javaClass) return false

    other as VerifiedData

    if (!clientData.contentEquals(other.clientData)) return false
    if (certificateChain != other.certificateChain) return false

    return true
  }

  override fun hashCode(): Int {
    var result = clientData.hashCode()
    result = 31 * result + certificateChain.hashCode()
    return result
  }
}
