/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5.1/userguide/building_java_projects.html
 */

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation("com.google.guava:guava:31.0.1-jre")

    // https://mvnrepository.com/artifact/com.squareup.wire/wire-runtime
    implementation("com.squareup.wire:wire-runtime:4.4.3")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api("org.apache.commons:commons-math3:3.6.1")
}

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.6.21"

    // Apply the java-library plugin for API and implementation separation.
    `java-library`

    id("com.squareup.wire") version "4.4.3"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

tasks.jar {
    manifest {
        attributes(mapOf("Implementation-Title" to project.name,
                         "Implementation-Version" to project.version))
    }
}

version = "0.1.0"

apply(plugin = "kotlin")

val protosSrc = "src/main/proto/"

repositories {
}

dependencies {
  implementation("org.bouncycastle:bcprov-jdk15to18:1.70")
  implementation("org.bouncycastle:bcpkix-jdk15to18:1.70")
  implementation("com.google.crypto.tink:tink:1.6.0")
  implementation("org.junit.jupiter:junit-jupiter:5.7.0")
}

wire {
  protoLibrary = true
  sourcePath {
    srcDir(protosSrc)
  }
  protoPath {
  }
  kotlin {
    javaInterop = true
  }
}
