use_frameworks!

platform :ios, '14.0'

target 'Trifle_Example' do
  pod 'Trifle', :path => '../../'

  target 'Trifle_Tests' do
    inherit! :search_paths

  end
end

target 'Trifle_macOS_Dummy' do
  platform :macos, '10.15'
  
  pod 'WireCompiler', '5.2.1'
end
