use_frameworks!

platform :ios, '14.0'

target 'SecuritySdk_Example' do
  pod 'semver', '~> 1.1'
  pod 'SecuritySdk', :path => '../'

  target 'SecuritySdk_Tests' do
    inherit! :search_paths

  end
end
